(defun my-docbook-settings()
    (interactive)
    (setq sgml-indent-step 1)
    (setq sgml-indent-data t)
    (setq indent-tabs-mode nil)
    (setq sgml-default-dtd-file nil)
)
;(require 'recentf)
;(recentf-mode 1)
(defun add-search-dir (path)
(setq load-path (cons (expand-file-name path) load-path)))
(add-search-dir "~/lib/emacs/lisp")
(load "php-style" t t)
;(load "gallery-template-mode" t t)

(setq auto-mode-alist (cons '("\\.r$" . c-mode) auto-mode-alist))

(require 'column-marker)

(setq py-start-run-py-shell nil)
(global-font-lock-mode t)
(setq font-lock-maximum-decoration t)
(define-key esc-map "[3~" 'delete-char)
(define-key global-map [kp-0] "0")
(define-key global-map [kp-1] "1")
(define-key global-map [kp-2] "2")
(define-key global-map [kp-3] "3")
(define-key global-map [kp-4] "4")
(define-key global-map [kp-5] "5")
(define-key global-map [kp-6] "6")
(define-key global-map [kp-7] "7")
(define-key global-map [kp-8] "8")
(define-key global-map [kp-9] "9")
(define-key global-map [kp-separator] "+")
(define-key global-map [kp-enter] "
")
(define-key global-map [select] 'end-of-line)
(define-key global-map (kbd "ESC <up>") 'beginning-of-buffer)
(define-key global-map (kbd "ESC <down>") 'end-of-buffer)
